Adding 'skip cascading deletion' feature when force deleting unreachable cluster and creating a new test
slateci/slate-client-server pull request #161
Opened 2021-09-07 19:19 UTC by pcjorgensen

Closes #140 

When attempting to delete an unreachable cluster slate may fail to delete it or wait a long time for timeouts to run on object deletion. 

With this change, if a cluster cannot be reached then it will notify the user and '--force' must be provided to delete the cluster records. This will speed up deletion and ensure that the records can always be deleted if standard deletion fails. If the cluster still exists then objects may remain on the backend which must be manually deleted. 

Also adds a test to check if an unreachable cluster can have its record deleted. The test will attempt to shut down the kubelet or minikube depending on the environment, run a --force delete, then restarts kubelet/minikube and does full deletion.

Fixes a bug in which deletion tests will always pass even if the components are unreachable.

2021-09-07 20:28 UTC, cnweaver commented
> The test will attempt to shut down the kubelet or minikube depending on the environment, run a --force delete, then restarts kubelet/minikube and does full deletion.

This sounds dangerous; if multiple tests are running concurrently, won't this pull the cluster out from under the others? Also, if the tests are being run on a shared cluster, this seems very disruptive. In fact, looking at the code, it looks like in its current state it will unconditionally disrupt both `minikube` and `kubelet` on the host system, whether or not either is being used by the test. 

Perhaps there's some safer and lighter-weight way to simulate a failure. Could the test perhaps reach directly into its Dynamo instance and fudge the address of the test cluster to ensure incorrectness (and then put it back when it wants the cluster to become accessible again). I'm imagining rewriting the address to be on the reserved `invalid` domain, or similar. 

I'm also confused about several aspects the functionality being implemented here. Is cascading deletion actually being skipped as various comments and log messages suggest? That seems really bad: If the cluster record is deleted without deleting all (instance, secret, volume, etc.) records which refer to it, those records are corrupt and can't be handled sensibly. From the code it looks more like what this actually does is (correctly) do the cascading deletion, but only within the database. (This unavoidably leaves actual resources danging, as the description already acknowledges, but this feature is mostly used when the cluster has already been destroyed one way or another, making the concern moot.) As a related question, what does it mean for the test to do 'full' deletion after the cluster is restored to accessibility? At that point, the API server should no longer have any knowledge of the cluster (having just deleted all related records), so the fact that it could reach it is irrelevant since it no longer knows how. In any case, the part of the test with the comment 'perform full deletion' doesn't appear to actually delete anything, just recheck the old response left over from when the deletin request was issued and the cluster was unavailable. Following from this, I would not expect the check for the namespace being cleaned up to pass; if anything the namespace should be expected to still be present exactly because the API server couldn't delete it. 

In `deleteCluster`, the standard deletions are gaurded by checks that the cluster can be reached; this makes sense. However, the 'database only' deletions are not protected by the reverse requirement. I think they should be because as it is if the cluster is contactable there is now a race between the two independent commands both deleting aspects of each item. If the 'true' deletion gets there first, things will be fine, but if the database deletion gets there first, the 'true' deletion will be operating on a thing the API server has lost its knowledge of. I _think_ this won't crash or anything because the in-memory representation of the object will still be around, but it feels like this violates the implicit invariant that nothing should be removed from the PersistentStore until the server is completely done with it. It would make more sense to me have `deleteThing` internally call `deleteThingFromStore` (restoring its old functionality), and only invoke the more minimal `deleteThingFromStore` from `deleteCluster` when `contactable` is `false` (which boils down to just adding an `else` to each of the pairs of async calls there). Also, I think without fixing this a bug is otherwise being introduced that a direct API request to delete a Thing is resulting in only the true object being removed from Kubernetes, but the SLATE record remaining around, impossible to remove. (E.g. `::deleteSecret` still just calls `internal::deleteSecret`, which as this patch stands does only the first half of the job, skipping the second).

2021-09-07 20:29 UTC, cnweaver requested changes
> The test will attempt to shut down the kubelet or minikube depending on the environment, run a --force delete, then restarts kubelet/minikube and does full deletion.

This sounds dangerous; if multiple tests are running concurrently, won't this pull the cluster out from under the others? Also, if the tests are being run on a shared cluster, this seems very disruptive. In fact, looking at the code, it looks like in its current state it will unconditionally disrupt both minikube and kubelet on the host system, whether or not either is being used by the test.

Perhaps there's some safer and lighter-weight way to simulate a failure. Could the test perhaps reach directly into its Dynamo instance and fudge the address of the test cluster to ensure incorrectness (and then put it back when it wants the cluster to become accessible again). I'm imagining rewriting the address to be on the reserved invalid domain, or similar.

I'm also confused about several aspects the functionality being implemented here. Is cascading deletion actually being skipped as various comments and log messages suggest? That seems really bad: If the cluster record is deleted without deleting all (instance, secret, volume, etc.) records which refer to it, those records are corrupt and can't be handled sensibly. From the code it looks more like what this actually does is (correctly) do the cascading deletion, but only within the database. (This unavoidably leaves actual resources danging, as the description already acknowledges, but this feature is mostly used when the cluster has already been destroyed one way or another, making the concern moot.) As a related question, what does it mean for the test to do 'full' deletion after the cluster is restored to accessibility? At that point, the API server should no longer have any knowledge of the cluster (having just deleted all related records), so the fact that it could reach it is irrelevant since it no longer knows how. In any case, the part of the test with the comment 'perform full deletion' doesn't appear to actually delete anything, just recheck the old response left over from when the deletin request was issued and the cluster was unavailable. Following from this, I would not expect the check for the namespace being cleaned up to pass; if anything the namespace should be expected to still be present exactly because the API server couldn't delete it.

In deleteCluster, the standard deletions are gaurded by checks that the cluster can be reached; this makes sense. However, the 'database only' deletions are not protected by the reverse requirement. I think they should be because as it is if the cluster is contactable there is now a race between the two independent commands both deleting aspects of each item. If the 'true' deletion gets there first, things will be fine, but if the database deletion gets there first, the 'true' deletion will be operating on a thing the API server has lost its knowledge of. I think this won't crash or anything because the in-memory representation of the object will still be around, but it feels like this violates the implicit invariant that nothing should be removed from the PersistentStore until the server is completely done with it. It would make more sense to me have deleteThing internally call deleteThingFromStore (restoring its old functionality), and only invoke the more minimal deleteThingFromStore from deleteCluster when contactable is false (which boils down to just adding an else to each of the pairs of async calls there). Also, I think without fixing this a bug is otherwise being introduced that a direct API request to delete a Thing is resulting in only the true object being removed from Kubernetes, but the SLATE record remaining around, impossible to remove. (E.g. ::deleteSecret still just calls internal::deleteSecret, which as this patch stands does only the first half of the job, skipping the second).

2021-09-07 20:53 UTC, pcjorgensen commented
1. So to your first two paragraphs, that's a really good point. As of right now running these tests on a shared cluster would disrupt the current state of the system, so it would be best to find a way around that.

2. Part of the changes we made ensure that when a '--force' flag is added, an unreachable cluster will have all components deleted from the database, including secrets and instances. To verify this functionality, we disabled minikube/kubelet before running an HTTP delete cluster request with an '&force' flag in TEST(ForceDeletingUnreachableCluster) then re-enabled it after checking dynamodb. Since there's no way to delete objects with minikube/kubelet disabled, this ensures that either database objects are deleted as expected when using the '--force' flag. 

3. We split up database deletion and object deletion, so object deletion will always run first and will pass if reachable. After it passes then it moves on to run database deletion. If it fails then it will return an error saying the cluster is unreachable. If the '--force' flag is added, and the cluster is verified to be unreachable, then database entries will be deleted and object deletion is skipped.

So deletion should work properly and not leave hanging database entries unless there's something we missed, but it would definitely be a problem if this test was run in production since it disables the kubelet.

2021-09-09 03:04 UTC, cnweaver commented
This doesn't currently compile (due to a minor mistake: `src/client/Client.cpp:1309:96: error: ‘endl’ was not declared in this scope`), it would be good to compile and test this before a re-review. 

> So deletion should work properly and not leave hanging database entries unless there's something we missed

This is definitely still an issue. For example, `::deleteSecret` continues to call `internal::deleteSecret`, but the latter is now broken and deletes only the backing Kubernetes secret object, without changing the PersistentStore. The fact that the related tests (e.g. `test-secret-deletion`) is only because those tests are flawed and aren't checking that the deleted object is gone from the API after the deletion has 'succeeded'. (This is a separate issue, but all tests of this type should be updated to deal with this; I don't know why I forgot it in the first place.) In the case of the secret deletion test, patching it as follows leads to a revelatory failure:

```Index: ../test/TestSecretDeletion.cpp
===================================================================
--- ../test/TestSecretDeletion.cpp	(revision 1624)
+++ ../test/TestSecretDeletion.cpp	(working copy)
@@ -77,11 +77,25 @@
 		ENSURE_CONFORMS(data,schema);
 		secretID=data["metadata"]["id"].GetString();
 	}
+	std::cout << "Got secret ID " << secretID << std::endl;
 	
 	{ //delete the secret
 		auto delResp=httpDelete(tc.getAPIServerURL()+"/"+currentAPIVersion+"/secrets/"+secretID+"?token="+adminKey);
 		ENSURE_EQUAL(delResp.status,200,"Secret deletion should succeed");
 	}
+
+	{ //list
+		auto listResp=httpGet(tc.getAPIServerURL()+"/"+currentAPIVersion+"/secrets?token="+adminKey+"&group="+groupName);
+		ENSURE_EQUAL(listResp.status,200, "Portal admin user should be able to list secrets");
+
+		ENSURE(!listResp.body.empty());
+		std::cout << "Listing response: " << listResp.body << std::endl;
+		rapidjson::Document data;
+		data.Parse(listResp.body.c_str());
+
+		//should be no secrets left
+		ENSURE_EQUAL(data["items"].Size(),0,"There should be no secrets returned");
+	}
 }```

2021-10-01 03:37 UTC, cnweaver requested changes
Allowing any user to change the server's caching period when adding a cluster is very bad and must be removed. The correct way to to approach this is to 1) update [the CLI configurtion code](https://github.com/slateci/slate-client-server/blob/skipCascadingDeletion/src/slate_service.cpp#L110) to support setting the cache validity period(s) with options, 2) set those on the `PersistentStore` after it is constructed, and 3) change the test to set the new option(s) on the server that it starts via the `TestContext`, using the support it [already has for setting options](https://github.com/slateci/slate-client-server/blob/skipCascadingDeletion/test/test.h#L147). 

The breakage of all of the other API object's user-facing deletion functions is also a blocking issue and must be resolved.

2021-10-06 16:40 UTC, closed without merging